
export default function Ex06() {
  return (
    <div>
        <div className="w-[500px] h-[200px] overflow-y-scroll border p-4">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam possimus alias aperiam saepe omnis excepturi! Eveniet consequuntur non accusamus facere consequatur nihil earum, culpa numquam quae officia fugit vero voluptatum!
            Quam architecto quasi vel consequuntur natus inventore quaerat aspernatur nostrum sit dignissimos, dolore laudantium. Ad odio nesciunt iure ex consectetur, non consequatur quidem harum obcaecati repellat pariatur voluptates facere cupiditate!
            Minus maxime quis sunt cupiditate amet sit blanditiis dolores delectus illum dolorem aliquam provident unde perspiciatis consectetur optio esse eius, non atque debitis fugiat voluptas deleniti magnam nulla nam! Quos!
            Nihil pariatur magni quisquam ipsam. Illum ut corrupti optio repellendus doloremque autem enim itaque excepturi consequatur, consequuntur iure id iusto minus natus suscipit vitae facere laborum quas ex! Nisi, harum.
            Aspernatur tempore aliquid odio ipsum ducimus voluptas placeat quos voluptates quibusdam quia non accusamus, exercitationem facere nemo distinctio! Corrupti cupiditate animi assumenda at, veniam voluptate vero quos deleniti laborum accusamus.
            Libero accusamus aut unde odit omnis voluptatibus excepturi. Dicta eos, voluptates dolor officiis quo consequuntur repudiandae, cumque maxime ducimus aut tempora, accusantium beatae modi tempore magni sunt perferendis omnis! Maiores!
            Dignissimos illum excepturi aspernatur? Perspiciatis at dolores nihil assumenda et exercitationem ullam, eos pariatur, perferendis dignissimos quae a possimus voluptates. Autem ut nesciunt alias commodi ea reprehenderit ullam sunt labore!
            Id obcaecati sunt soluta voluptas eligendi. Maxime odio amet laborum voluptatum, nesciunt dolorem error omnis illo magni eos quia, qui id dolorum sapiente blanditiis est officia repellat delectus iste soluta!
            Harum explicabo maiores autem incidunt eligendi, iure a reprehenderit, laboriosam perferendis nam nihil maxime architecto! Esse eos enim quam, maxime voluptas similique reiciendis harum consectetur quo omnis laborum magnam ducimus.
            Similique consequatur, sequi incidunt ipsum consequuntur eveniet error quos ex iusto sed tempore neque nesciunt omnis et, ratione deserunt vel officiis exercitationem velit atque veritatis! Eaque a reiciendis voluptatibus repellat.
            Totam fugit expedita hic quas, voluptatum cupiditate voluptatem sunt tempora, temporibus dolore illum! Exercitationem ab sint suscipit incidunt corporis eos, dolorum, reiciendis excepturi aliquam blanditiis repellendus vitae, corrupti sit veritatis!
            Maiores minima ullam, sapiente cupiditate eligendi neque corrupti ducimus officia distinctio et, corporis, totam sequi accusantium cumque doloremque provident. Assumenda enim eligendi voluptatibus dolor itaque delectus voluptas impedit nam nihil!
            Dicta, reiciendis? In unde quo nemo nobis temporibus porro asperiores, perspiciatis cupiditate quis reprehenderit, nostrum provident sunt quam, voluptate nesciunt ad? Quibusdam distinctio ratione aliquid debitis consectetur ut cum corporis.
            Delectus quaerat ipsam accusantium sunt debitis deserunt unde ad saepe, provident atque nam sit earum optio, laudantium eligendi quasi id quidem veritatis beatae natus. Natus similique enim debitis dolor architecto!
            Porro eos voluptatum, eligendi hic eum molestiae enim facilis rerum, ducimus accusantium, animi ratione officiis dolore iure laboriosam. Nesciunt debitis architecto itaque odit esse necessitatibus dolorem libero magni voluptatum ex.
            Laudantium, nemo. Animi laboriosam vitae dignissimos harum doloremque sint, impedit cum nulla in inventore veritatis non illum! Quibusdam debitis labore, hic vero praesentium, quas laborum ipsum velit iste ut nesciunt.
            Accusamus quam soluta at reprehenderit sint, molestias itaque sit, consequatur amet odit laudantium optio repellendus. Alias obcaecati similique nesciunt rerum exercitationem quia repellat ullam molestiae, ab voluptatum autem atque ipsa!
            Illo assumenda aspernatur earum tenetur. Quam quia voluptas nam corrupti quibusdam, est laudantium illum! Nostrum aspernatur aut tempore qui sapiente ea reiciendis nisi? Velit laudantium voluptatem accusantium tempore, doloremque autem?
            Ipsam non sed cumque in molestias asperiores consectetur aut sequi voluptas et obcaecati unde ad facilis perferendis esse, nihil accusamus, harum neque rerum repellendus eveniet inventore dolorem dolor nemo! Praesentium!
            Unde voluptatum facere aut ad laudantium! Molestiae culpa odio aliquid optio est nesciunt fuga iste rem repellat animi esse ad nihil repellendus ducimus similique consequuntur saepe veritatis tempora, numquam voluptatem?
            Asperiores accusamus sapiente ab vero. Eos nobis porro adipisci. Dignissimos id maiores, molestiae, facere, voluptates dolore temporibus deserunt ipsum neque iusto impedit omnis voluptatibus! Voluptatibus dicta hic quia non! Nam.
            Corrupti pariatur delectus animi libero tempora error perferendis architecto illum voluptates tenetur assumenda repellat quae quod quibusdam, nesciunt placeat! Corporis quidem dolorum architecto odio vitae modi itaque libero deserunt iste.
            Architecto assumenda alias laudantium? Velit esse repudiandae voluptates reiciendis assumenda facere aperiam, doloremque sapiente! Officiis consequuntur at libero eos voluptatum, odio debitis fuga nisi. Blanditiis suscipit quis fugiat nihil quasi.
            Voluptatum possimus blanditiis illum nemo rerum minus deleniti, vitae rem laboriosam doloremque reiciendis, odit necessitatibus a repellendus beatae dolores. Reiciendis culpa id mollitia debitis voluptate rerum necessitatibus eaque at? Minus.
            Harum architecto, voluptatibus alias molestiae veritatis, adipisci repudiandae sapiente, iste odit iusto quidem placeat? Itaque, dolore officia. Quidem quae deserunt animi facere tempora amet qui quibusdam. Quia quam rem cupiditate.
            Ipsum voluptate assumenda placeat necessitatibus minima? Beatae impedit, ad asperiores voluptatibus nesciunt reprehenderit corrupti ex animi, praesentium, molestiae ut tempora! Hic maiores numquam reiciendis, voluptas deserunt molestias delectus quidem repudiandae!
            Possimus maxime consequuntur rerum laborum, unde culpa, optio minus exercitationem modi quisquam doloremque dignissimos architecto distinctio tempore non sint enim est similique ad sed qui reprehenderit ut tenetur suscipit. Vitae?
            Nemo nesciunt quaerat unde architecto consequuntur a quibusdam repudiandae! Debitis aspernatur rerum atque obcaecati iure velit at! Numquam perferendis et odio dolorem. Amet nobis harum obcaecati? Pariatur excepturi maiores dolore!
            Explicabo consectetur quam velit fuga libero obcaecati excepturi facilis et nihil blanditiis beatae quia, sunt rerum ab aliquid porro magni numquam nesciunt deleniti ipsum dolores tenetur illo dignissimos. Vitae, explicabo.
            Reprehenderit asperiores excepturi minima ullam consequuntur veniam exercitationem, sit accusantium a facilis nulla harum odit doloremque dolorum optio beatae, aliquam minus porro debitis deserunt voluptate numquam temporibus dolore repellat. Aperiam.
            Voluptatibus id quod nesciunt reprehenderit facere. Ad, accusantium blanditiis quas quos quod ipsam? Ab labore dolores voluptatem dolorum, dolorem quaerat rerum perferendis reprehenderit modi quidem, numquam sequi. Esse, nostrum dicta?
            Est pariatur odio assumenda molestias libero corporis soluta facere, laborum ad? Beatae libero error soluta, iure doloremque in obcaecati optio repellat quo? Earum laboriosam amet voluptate consequuntur ratione architecto odio.
            Culpa delectus harum molestias sunt voluptate necessitatibus id, modi cupiditate, rerum, illum veniam assumenda nihil. Magni placeat alias ea quisquam est architecto. Laborum optio quo mollitia dolores necessitatibus dicta facere!
            Non, ratione totam facilis, voluptatem dolorem adipisci exercitationem dolore, optio sit voluptatibus cumque unde nemo cum. Explicabo, incidunt quo amet similique porro maiores ipsum. Voluptatum ratione nihil suscipit nulla rem.
            Assumenda officia, quia aliquid molestiae magni ab ducimus reprehenderit? Dolorem laudantium enim, exercitationem quam quas atque corrupti explicabo commodi distinctio vitae deserunt harum adipisci hic, voluptates qui assumenda non magnam!
            Praesentium, accusamus corporis ipsa assumenda obcaecati quod temporibus, cumque repellendus consequuntur nisi, voluptatem quidem fugit fuga eveniet laudantium veniam asperiores ab totam ut? Rerum, quibusdam eius! Eaque nisi dicta accusantium!
            Esse officiis blanditiis error voluptatibus modi, quasi nemo pariatur libero commodi adipisci dolores eius architecto qui dicta quos ipsum quibusdam animi ea sapiente nesciunt culpa. Soluta veniam est maxime atque?
            Saepe labore autem totam repudiandae quia voluptatem ipsum numquam ipsa, iure officia eum veritatis, quisquam tempore similique ad. Tempora optio quibusdam reiciendis! Culpa vitae perspiciatis, asperiores itaque repellendus dolore sequi!
            Blanditiis amet, neque eaque corrupti possimus soluta dicta eos architecto esse id voluptas vero odio sed accusantium iusto! Qui modi necessitatibus dicta repellendus maiores fugiat optio asperiores amet adipisci debitis?
            Obcaecati impedit ipsa quod veniam eveniet labore nisi nulla atque natus laborum voluptatem consectetur eius, vitae quos ipsum repudiandae omnis amet error tempore nemo, dolorem pariatur sed ut. Quo, quasi.
            At, neque est accusantium repellendus accusamus, exercitationem quaerat sit tempore eligendi voluptas necessitatibus illum iure totam culpa commodi ipsam maiores, rerum asperiores praesentium aliquid ea inventore magni! Provident, vel aperiam.
            Itaque reiciendis ad quos tenetur, deleniti quisquam iusto dolores. Vel incidunt soluta velit, doloremque assumenda debitis explicabo corporis optio dolorum placeat iure vitae. Vel magnam similique in aliquid expedita voluptatibus!
            Praesentium vitae itaque modi, explicabo totam dolor natus. Molestiae labore praesentium recusandae laudantium voluptate ipsum, quam commodi, alias eaque suscipit ad. Delectus qui tempore dolore est, in dolorum mollitia ex?
            Qui explicabo, recusandae aperiam dolores magnam reprehenderit blanditiis, dolor nemo temporibus perferendis ut voluptatum quisquam distinctio consectetur architecto, provident ducimus fugit officia velit porro aliquam! Quisquam nemo ipsum praesentium voluptatem.
            Sapiente in soluta quasi quibusdam aliquam. Cumque cupiditate odit nostrum vel assumenda exercitationem nam soluta? Asperiores vero aspernatur molestiae voluptates, unde exercitationem. Sit nostrum et praesentium ipsum sunt cumque rerum!
            Est accusantium impedit laudantium ullam quidem, fugit rem, autem omnis tempora doloribus iusto, commodi quia eveniet consequuntur veritatis itaque provident. Nemo, rem nam minus fugiat suscipit voluptate quod accusamus. Eum.
            Facilis voluptates doloremque perspiciatis ad tempore sit pariatur repellendus mollitia, dolor aspernatur voluptatum quo quasi ducimus corporis alias laborum aliquid minus nesciunt vitae est laboriosam! Quam ratione enim aliquid nulla?
            Aliquid quidem aperiam quam eveniet enim cum rerum alias eos eius quod. Corporis doloremque pariatur similique eos labore nulla tenetur, expedita amet assumenda facere totam a doloribus natus iste aliquid?
            Illum suscipit eaque soluta iste doloribus natus magni quos ex quod! Neque ex, consectetur odit delectus quae dicta. Dolorum rem accusantium quae maiores sed amet, eaque ut nostrum officia in.
            Corporis, suscipit modi cupiditate iste similique ut officiis assumenda laboriosam culpa labore eligendi dolorum fuga sint provident quia ratione minima. Delectus rerum ad iure maxime accusantium eius repellat saepe hic.</p>
        </div>
    </div>
  )
}
